name: CI

on: [push, pull_request]

jobs:
  
  linux:
    runs-on: ubuntu-20.04
    container:
      image: swift:latest
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: swift --version
      - name: Build and Test
        run: swift build -c release --product LyricsCLI